apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: codebrothers-customer-deployment
spec:
  selector:
    matchLabels:
      app: codebrothers-customer
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: codebrothers-customer
    spec:
      containers:
      - name: codebrothers-customer
        image: codebrothers-customer:latest
        ports:
        - containerPort: 8081