version: '3'

services:
  postgresql-code-brother:
    image: 'codebrothers/postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      POSTGRES_PASSWORD: "CodeBrother@2020"
    networks:
      - postgres-network

  pgadmin-code-brother:
    image: 'marcosjlima/pgadmin-codebrothers:1'
    environment:
      PGADMIN_DEFAULT_EMAIL: "codebrother@codebrother.com.br"
      PGADMIN_DEFAULT_PASSWORD: "CodeBrother@2020"
    ports:
      - "16543:80"
    depends_on:
      - postgresql-code-brother
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge

volumes:
  postgresql_data:
    driver: local