apiVersion: v1
kind: Service
metadata:
  name: postgresql-code-brother
  labels:
    app: postgresql-code-brother
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgresql-code-brother