version: '3'

services:
  postgresql-code-brother:
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    volumes:
      - /database/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "CodeBrother@2020"
      PGDATA: /var/lib/postgresql/data/report
    networks:
      - postgres-network

  pgadmin-code-brother:
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: "codebrother@codebrother.com.br"
      PGADMIN_DEFAULT_PASSWORD: "CodeBrother@2020"
    ports:
      - "16543:80"
    depends_on:
      - postgresql-code-brother
    networks:
      - postgres-network
    
  rabbitmq-code-brother:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'
    depends_on:
      - postgresql-code-brother
    networks:
      - postgres-network

  eureka-code-brother:
    image: "codebrothers/codebrothers.eureka"
    ports:
      - "8761:8761"    
    depends_on:
      - postgresql-code-brother
    networks:
      - postgres-network  

networks: 
  postgres-network:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
  rabbitmq_data:
    driver: local