CREATE DATABASE "CodeBrothers_Customer"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

CREATE TABLE tb_customer
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ativo boolean NOT NULL DEFAULT true,
    atualizadoem timestamp without time zone,
    cpf character varying(14) COLLATE pg_catalog."default" NOT NULL,
    criadoem date NOT NULL DEFAULT CURRENT_DATE,
    datanascimento date,
    email character varying(50) COLLATE pg_catalog."default",
    nome character varying(30) COLLATE pg_catalog."default" NOT NULL,
    rg character varying(12) COLLATE pg_catalog."default",
    sobrenome character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tb_customer_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE tb_customer OWNER to postgres;

CREATE TABLE tb_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(50) COLLATE pg_catalog."default",
    nome character varying(30) COLLATE pg_catalog."default" NOT NULL,
    password character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT tb_user_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE tb_user OWNER to postgres;