kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-code-brother
  labels:
    type: local
    app: rabbitmq-code-brother
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-code-brother
  labels:
    app: rabbitmq-code-brother
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi